import { MaterialIconStyle } from "@/components/Icon";
import { baseUrl } from "@/constants";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (<html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="theme-bg" />
        <main className="z-10 pb-96 max-w-xl mx-auto flex-auto min-w-0 mt-6 flex flex-col px-6">
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </main>

        <MaterialIconStyle />
      </body>
    </html>
  );
}
